#pragma once

#define TINYOBJLOADER_IMPLEMENTATION
#define GLM_ENABLE_EXPERIMENTAL
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLFW_INCLUDE_VULKAN
#define STB_IMAGE_IMPLEMENTATION

const int MAX_FRAMES_IN_FLIGHT = 3;
